{{ if and .Values.route.enabled (not .Values.ingress.enabled) -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $.Release.Name }}-discrete-ingestion-db-route
spec:
  to:
    kind: Service
    name: {{ $.Release.Name }}discrete-ingestion-db-service
{{ end }}