apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: master-ingress
  annotations:
    nginx.org/mergeable-ingress-type: "master"
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: "localhost"
