{{ if .Values.gitSync.enabled }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-nifi-registry-config-map
data:
  {{- with .Values.gitSync }}
  providers.xml: |+
    <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
    <providers>
        <flowPersistenceProvider>
            <class>org.apache.nifi.registry.provider.flow.git.GitFlowPersistenceProvider</class>
            <property name="Flow Storage Directory">{{ .root }}</property>
            <property name="Remote To Push">origin</property>
            <property name="Remote Access User">{{ .username }}</property>
            <property name="Remote Access Password">{{ .password }}</property>
            <property name="Remote Clone Repository">{{ .repo }}</property>
        </flowPersistenceProvider>

        <extensionBundlePersistenceProvider>
            <class>org.apache.nifi.registry.provider.extension.FileSystemBundlePersistenceProvider</class>
            <property name="Extension Bundle Storage Directory">./extension_bundles</property>
        </extensionBundlePersistenceProvider>
    </providers>
  {{- end -}}
{{ end }}