
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nifi-registry-service
spec:
  selector:
    podName: {{ .Release.Name }}-nifi-registry-pod
  ports:
  - protocol: TCP
    port: 18080
    targetPort: 18080
