apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      podName: {{ .Release.Name }}-{{ .Chart.Name }}-pod 
  template:
    metadata:
      labels:
        podName: {{ .Release.Name }}-{{ .Chart.Name }}-pod
    spec:
      containers:
      - name: {{ .Release.Name }}-{{ .Chart.Name }}-container
        env:
        - name: LANGUAGE
          value: {{ tpl .Values.language . | 'en' }}
        - name: SERVICE_PROTOCOL
          value: {{ .Values.serviceProtocol | quote }}
        - name: SERVICE_NAME
          value: {{ .Values.serviceName | quote }}
        - name: MODEL_SERVICE_URL
          value: {{ tpl .Values.modelServiceUrl . | quote }}
        - name: MODEL_SERVICE_NAME
          value: {{ tpl .Values.modelServiceName . | quote }}
        - name: JOB_SERVICE_URL
          value: {{ tpl .Values.jobServiceUrl . | quote }}
        - name: JOB_SERVICE_NAME
          value: {{ tpl .Values.jobServiceName . | quote }}
        image: {{ .Values.image }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.port }}
