ingress:
  enabled: true

  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: "minion"
    nginx.org/rewrites: "serviceName={{ .Release.Name }}-{{ .Chart.Name }}-service rewrite=/"

  path: "/nifi-registry/"
    
  host: "minikube.local"


route:
  enabled: false

image: apache/nifi-registry:latest

gitSync:
  enabled: true
  repo: https://github.com/MapColonies/3d-nifi-ingestion-flow.git
  root: ./flow_storage
  username: user
  password: token
