ingress:
  enabled: true

  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    # nginx.org/mergeable-ingress-type: "minion"
    
  host: "minikube.local"


route:
  enabled: false

image: apache/nifi-registry:latest

gitSync:
  enabled: true
  repo: https://github.com/MapColonies/3d-nifi-ingestion-flow.git
  root: ./flow_storage
  username: user
  password: token
