{{- $deploymentName := print .Release.Name "-" .Chart.Name "-deployment" -}}
{{- $podName := print .Release.Name "-" .Chart.Name "-pod" -}}
{{- $containerName := print .Release.Name "-" .Chart.Name "-container" -}}
{{- $resourcePV := print .Release.Name "-" .Chart.Name "-pv" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: {{ $deploymentName }}
  name: {{ $deploymentName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ $podName }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: {{ $podName }}
    spec:
      containers:
      - env:
        - name: MINIO_ROOT_USER
          value: {{ .Values.username }}
        - name: MINIO_ROOT_PASSWORD
          value: {{ .Values.password }}
        image: {{ .Values.image }}
        name: {{ $containerName }}
        args: ["server", {{ .Values.dataDirPath }}"]
        ports:
        - containerPort: 9000
        resources: {}
        volumeMounts:
        - mountPath: {{ .Values.dataDirPath }}
          name: {{ $resourcePV }}
      restartPolicy: Always
      volumes:
      - name: {{ $resourcePV }}
        persistentVolumeClaim:
          claimName: {{ $resourcePV }}
status: {}
