{{- $resourcePV := print .Release.Name "-" .Chart.Name "-pv" -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $resourcePV }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volume.storage }}