{{- $serviceName := print .Release.Name "-" .Chart.Name "-service" -}}
{{- $deploymentName := print .Release.Name "-" .Chart.Name "-deployment" -}}
{{- $podName := print .Release.Name "-" .Chart.Name "-pod" -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ $serviceName }}
  name: {{ $serviceName }}
spec:
  ports:
  - port: 9000
    targetPort: 9000
  selector:
    name: {{ $podName }}
