
# The port on which the service should listen
port: 8080

# Name of the image tu pull from registry
image: mapcolonies/3d-ingestion-catalog:v1.1.0

postgis:
  host: ingestion-stack-postgis
  port: 5432
  volume:
    storage: 500Mi
  db_name: postgres
  authentication:
    username: postgres
    password: postgres

  enabled: false
  # needed in case local deployment is enabled
  # pg_data_path: /var/lib/postgresql/data/pgdata
  # image: postgis/postgis:12-3.0-alpine

ingress:
  enabled: true

  annotations:
    kubernetes.io/ingress.class: "nginx"
    # nginx.org/mergeable-ingress-type: "minion"
    nginx.ingress.kubernetes.io/rewrite-target: /$2

  host: "minikube.local"


route:
  enabled: false
