3d-model-ingestion-service:
  enabled: true

  jobServiceUrl: "http://{{ .Release.Name }}-discrete-ingestion-db-service:8080/jobs"
  flowServiceUrl: "http://{{ .Release.Name }}-nifi-service:8083"

3d-model-ingestion-client:
  enabled: true

  modelServiceUrl: "http://minikube.local/3d-model-ingestion-service/"
  modelServiceName: /models
  jobServiceUrl: "http://minikube.local/discrete-ingestion-db/"
  jobServiceName: /jobs

  ingress:
    enabled: true
    path: "/"
  route:
    enabled: true

discrete-ingestion-db:
  enabled: true

  postgis:
    host: "{{ .Release.Name }}-postgis"
    enabled: false

3d-ingestion-catalog:
  enabled: true

  postgis:
    host: "{{ .Release.Name }}-postgis"
    enabled: false

nifi:
  enabled: true

nifi-registry:
  enabled: true
  gitSync:
    enabled: true
    repo: https://github.com/MapColonies/3d-nifi-ingestion-flow.git
    root: ./flow_storage
    username: user
    password: password

postgis:
  enabled: true

minio:
  enabled: true

nginx-for-s3:
  enabled: true
  s3:
    host: "{{ .Release.Name }}-minio-service"
  
pycsw:
  enabled: true
  pycsw:
    config:
      server:
        profiles: mc3d
      repository:
        database: "postgresql://postgres:postgres@{{ .Release.Name }}-postgis/postgres"
