3d-model-ingestion-service:
  enabled: true

  # The port on which the service should listen
  port: 8080

  # Name of the image tu pull from registry
  image: mapcolonies/3d-model-ingestion-service:v1.1.3

  jobServiceUrl: "http://{{ .Release.Name }}-discrete-ingestion-db-service:8080/jobs"
  flowServiceUrl: "http://{{ .Release.Name }}-nifi-service:8083"

  ingress:
    enabled: true

  route:
    enabled: false

discrete-ingestion-db:
  enabled: true
  # The port on which the service should listen
  port: 8080

  # Name of the image tu pull from registry
  image: mapcolonies/discrete-ingestion-db:v2.0.0

  postgis:
    host: "{{ .Release.Name }}-postgis"
    port: 5432
    volume:
      storage: 500Mi
    db_name: postgres
    authentication:
      username: postgres
      password: postgres

    enabled: false

  ingress:
    enabled: true

  route:
    enabled: false

3d-ingestion-catalog:
  enabled: true
  # The port on which the service should listen
  port: 8080

  # Name of the image tu pull from registry
  image: mapcolonies/3d-ingestion-catalog:v1.1.0

  postgis:
    host: "{{ .Release.Name }}-postgis"
    port: 5432
    volume:
      storage: 500Mi
    db_name: postgres
    authentication:
      username: postgres
      password: postgres

    enabled: false

  ingress:
    enabled: true

  route:
    enabled: false


nifi:
  enabled: true
  ingress:
    enabled: true
  route:
    enabled: false

  image: apache/nifi:latest

  openServicePorts:
    enabled: true
    startPort: 8081
    numberOfPorts: 10

nifi-registry:
  enabled: true
  ingress:
    enabled: true
  route:
    enabled: false

  image: apache/nifi-registry:latest

  gitSync:
    enabled: true
    repo: https://github.com/MapColonies/3d-nifi-ingestion-flow.git
    root: ./flow_storage
    username: user
    password: password


postgis:
  enabled: true

  volume:
    storage: 500Mi
  db_name: postgres
  authentication:
    username: postgres
    password: postgres
  pg_data_path: /var/lib/postgresql/data/pgdata
  image: postgis/postgis:12-3.0-alpine

