route: 
  enabled: false
  tls: false
ingress: 
  enabled: true

  host: "minikube.local"

  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: "minion"
    nginx.org/rewrites: "serviceName={{ .Release.Name }}-{{ .Chart.Name }}-service rewrite=/"

  path: /pycsw/

postgres:
  enabled: false
  volume:
    storage: 500Mi
  db_name: postgres
  authentication:
    username: postgres
    password: postgres
  pg_data_path: /var/lib/postgresql/data/pgdata

pycsw:
  image: mapcolonies/pycsw:latest
  config:
    server:
      home: /home/pycsw
      url: http://localhost:8000
      mimetype: application/xml; charset=UTF-8
      encoding: UTF-8
      language: en-US
      maxrecords: 10
      loglevel: DEBUG
      logfile: " "
      # ogc_schemas_base: http://foo
      # federatedcatalogues: http://catalog.data.gov/csw
      # pretty_print: true
      # gzip_compresslevel: 8
      # domainquerytype: range
      # domaincounts: true
      # spatial_ranking: true
      profiles: mc3d
      # workers: 2
    manager:
      transactions: "false"
      allowed_ips: 127.0.0.1
      # csw_harvest_pagesize: 10
    metadata:
      identification_title: pycsw Geospatial Catalogue
      identification_abstract: pycsw is an OARec and OGC CSW server implementation written in Python
      identification_keywords: catalogue,discovery,metadata
      identification_keywords_type: theme
      identification_fees: None
      identification_accessconstraints: None
      provider_name: Organization Name
      provider_url: https://pycsw.org/
      contact_name: Lastname, Firstname
      contact_position: Position Title
      contact_address: Mailing Address
      contact_city: City
      contact_stateorprovince: Administrative Area
      contact_postalcode: Zip or Postal Code
      contact_country: Country
      contact_phone: +xx-xxx-xxx-xxxx
      contact_fax: +xx-xxx-xxx-xxxx
      contact_email: Email Address
      contact_url: Contact URL
      contact_hours: Hours of Service
      contact_instructions: During hours of service.  Off on weekends.
      contact_role: pointOfContact
    repository:
      # database: ${PYCSW_REPOSITORY_DATABASE_URI}
      database: postgresql://postgres:postgres@ingestion-stack-postgis/postgres
      table: records
      mappings: ${PYCSW_MAPPINGS_FILEPATH}
      # filter: type = 'http://purl.org/dc/dcmitype/Dataset'
    inspire:
      enabled: "false"
      languages_supported: eng,gre
      default_language: eng
      date: YYYY-MM-DD
      gemet_keywords: Utility and governmental services
      conformity_service: notEvaluated
      contact_name: Organization Name
      contact_email: Email Address
      temp_extent: YYYY-MM-DD/YYYY-MM-DD
  # In order to change default db columns mapping
  mappings_py: |+
    MD_CORE_MODEL = {
      'typename': 'pycsw:CoreMetadata',
      'outputschema': 'http://pycsw.org/metadata',
      'mappings': {
        # Needed fot PYCSW
        'pycsw:Identifier': 'identifier',
        'pycsw:Typename': 'typename',
        'pycsw:Schema': 'schema',
        'pycsw:MdSource': 'mdsource',
        'pycsw:InsertDate': 'insert_date',
        'pycsw:XML': 'xml',
        'pycsw:AnyText': 'anytext',
        'pycsw:BoundingBox': 'wkt_geometry',

        'pycsw:Title': 'title',
        'pycsw:AlternateTitle': 'title',
        'pycsw:Creator': 'producer_name',
        'pycsw:Abstract': 'description',
        'pycsw:Publisher': 'producer_name',
        'pycsw:Contributor': 'producer_name',
        'pycsw:Modified': 'creation_date',
        'pycsw:Date': 'creation_date',
        'pycsw:Type': 'type',
        'pycsw:Format': 'type',
        'pycsw:Keywords': 'keywords',
        'pycsw:Identifier': 'identifier',
        'pycsw:Source': 'producer_name',
        'pycsw:AccessConstraints': 'classification',
        'pycsw:CRS': 'srs',
        'pycsw:BoundingBox': 'wkt_geometry',
        'pycsw:AnyText': 'anytext',

        'pycsw:Relation': '',
        'pycsw:Language': '',
        'pycsw:Keywords': '',
        'pycsw:TopicCategory': '',

        # Added for mc3d
        'pycsw:projectName': 'project_name',
        'pycsw:Identifier': 'identifier',
        'pycsw:Title': 'title',
        'pycsw:version': 'version',
        'pycsw:centroid': 'centroid',
        'pycsw:footprint': 'footprint',
        'pycsw:BoundingBox': 'wkt_geometry',
        'pycsw:Classification': 'classification',
        'pycsw:TempExtent_begin': 'time_begin',
        'pycsw:TempExtent_end': 'time_end',
        'pycsw:sensorType': 'sensor_type',
        'pycsw:region': 'region',
        'pycsw:nominalResolution': 'nominal_resolution',
        'pycsw:accuracyLE90': 'accuracy_le_90',
        'pycsw:horizontalAccuracyCE90': 'horizontal_accuracy_ce_90',
        'pycsw:relativeAccuracyLE90': 'relative_accuracy_le_90',
        'pycsw:CreationDate': 'creation_date',
        'pycsw:Creator': 'producer_name',
        'pycsw:CRS': 'srs',
        'pycsw:validationDate': 'validation_date',
        'pycsw:estimatedPrecision': 'estimated_precision',
        'pycsw:measuredPrecision': 'measured_precision',
        'pycsw:Abstract': 'description',
        'pycsw:Links': 'links',
        'pycsw:Type': 'type',    
      }
    }
