{{- $resourceName := print .Release.Name "-postgis-pv" -}}
{{- with .Values }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: {{ $resourceName }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .volume.storage }}
status: {}
{{- end -}}
