
# The port on which the service should listen
port: 8080

# Name of the image tu pull from registry
image: mapcolonies/3d-model-ingestion-service:latest

jobServiceUrl: http://discrete-ingestion-db:8080/jobs
flowServiceUrl: http://nifi:8083

ingress:
  enabled: true

  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: "minion"
    nginx.org/rewrites: "serviceName={{ .Release.Name }}-{{ .Chart.Name }}-service rewrite=/"

  path: /3d-model-ingestion-service/

  host: "minikube.local"

route:
  enabled: false