ingress:
  enabled: true

  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: "minion"
    nginx.org/rewrites: "serviceName={{ .Release.Name }}-{{ .Chart.Name }}-service rewrite=/"

  path: "/nifi/"
  
  host: "minikube.local"
      
route:
  enabled: false

image: apache/nifi:latest

openServicePorts:
  enabled: true
  startPort: 8081
  numberOfPorts: 10
