apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-3d-ingetion-catalog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      podName: {{ .Release.Name }}-3d-ingetion-catalog-pod
  template:
    metadata:
      labels:
        podName: {{ .Release.Name }}-3d-ingetion-catalog-pod
    spec:
      containers:
      - name: {{ .Release.Name }}-3d-ingetion-catalog-container
        env:
        - name: DB_HOST
          {{ if .Values.postgis.enabled }}
          value: "{{ .Release.Name }}-postgis"
          {{ else }}
          value: {{ tpl .Values.postgis.host .| quote }}
          {{ end }}
        - name: DB_PORT
          value: {{ .Values.postgis.port | quote }}
        - name: DB_USER
          value: {{ .Values.postgis.authentication.username | quote }}
        - name: DB_PASSWORD
          value: {{ .Values.postgis.authentication.password | quote }}
        - name: DB_NAME
          value: {{ .Values.postgis.db_name | quote }}
        - name: SERVER_PORT
          value: {{ .Values.port | quote }}
        image: {{ .Values.image }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.port }}
