{{- $resourceConfigmap := print .Release.Name "-" .Chart.Name  "-configmap" }}
{{- $postgresName := print .Release.Name "-" .Chart.Name  "-postgres" }}
{{- $deploymentName := print .Release.Name "-" .Chart.Name  "-deployment" }}
{{- $podName := print .Release.Name "-" .Chart.Name  "-pod" }}
{{- $containerName := print .Release.Name "-" .Chart.Name  "-container" }}
{{- with .Values }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $deploymentName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ $podName }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: {{ $podName }}
    spec:
    {{- if .pycsw.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .pycsw.imagePullSecrets }}
    {{- end }}
      containers:
      - env:
        - name: PYCSW_SERVER_URL
          value: http://localhost:8000
        {{- if .postgres.enabled }}
        - name: PYCSW_REPOSITORY_DATABASE_URI
          value: postgresql://{{ .postgres.authentication.username }}:{{ .postgres.authentication.password }}@{{ $postgresName }}/{{ .postgres.db_name }}
        {{- end }}
        {{- if .pycsw.mappings_py }}
        - name: PYCSW_MAPPINGS_FILEPATH
          value: /etc/pycsw/mappings.py
        {{- end }}
        image: {{ .pycsw.image }}
        imagePullPolicy: IfNotPresent
        name: {{ $containerName }}
        ports:
        - containerPort: 8000
        resources: {}
        volumeMounts:
        - mountPath: /etc/pycsw
          name: {{ $resourceConfigmap }}
      restartPolicy: Always
      volumes:
      - name: {{ $resourceConfigmap }}
        configMap:
          name: {{ $resourceConfigmap }}
status: {}
{{- end -}}
