{{- $resourceName := print .Release.Name "-" .Chart.Name "-service" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $resourceName }}
spec:
  type: ClusterIP
  ports:
    - port: 8000
  selector:
    name: {{ .Release.Name }}-{{ .Chart.Name }}-pod
