apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      podName: {{ .Release.Name }}-{{ .Chart.Name }}-pod 
  template:
    metadata:
      labels:
        podName: {{ .Release.Name }}-{{ .Chart.Name }}-pod
    spec:
      containers:
      - name: {{ .Release.Name }}-{{ .Chart.Name }}-container
        env:
        - name: SERVER_PORT
          value: {{ .Values.port | quote }}
        - name: JOB_SERVICE_URL
          value: {{ tpl .Values.jobServiceUrl . | quote }}
        - name: FLOW_SERVICE_URL
          value: {{ tpl .Values.flowServiceUrl . | quote }}
        image: {{ .Values.image }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.port }}
