{{ if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-3d-model-ingestion-service-ingress
  annotations:
  {{- range $key, $val := .Values.ingress.annotations }}
    {{ $key }}: {{ $val }}
  {{- end }}
spec:
  rules:
  - http:
      paths:
      - path: /{{ .Release.Name }}/3d-model-ingestion-service(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-3d-model-ingestion-service-service
            port:
              number: 8080
    {{- if .Values.ingress.host }}
    host: {{ .Values.ingress.host }}
    {{ end }}
{{ end }}