{{ if and .Values.route.enabled (not .Values.ingress.enabled) -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $.Release.Name }}-{{ .Chart.Name }}-route
spec:
  path:  {{ .Values.route.path }}
  to:
    kind: Service
    name: {{ .Release.Name }}-{{ .Chart.Name }}-service
{{ end }}