{{- $ingressPath := (.Values.ingress.path | default (print .Release.Name "/" .Chart.Name "/")) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nifi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      podName: {{ .Release.Name }}-nifi-pod
  template:
    metadata:
      labels:
        podName: {{ .Release.Name }}-nifi-pod
    spec:
      containers:
      - name: {{ .Release.Name }}-nifi-pod-container
        image: {{ .Values.image }}
        imagePullPolicy: IfNotPresent
        env:
        - name: NIFI_WEB_PROXY_CONTEXT_PATH
          value: {{ $ingressPath | quote }}
        ports:
        - containerPort: 8080
