{{ if .Values.ingress.enabled -}}
{{- $ingressPath := (.Values.ingress.path | default (print .Release.Name "/" .Chart.Name "/")) -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-nifi-ingress
  annotations:
  {{- range $key, $val := .Values.ingress.annotations }}
    {{ $key }}: {{ tpl $val $ }}
  {{- end }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
        proxy_set_header 'X-ProxyContextPath' '{{ $ingressPath }}';
        proxy_set_header 'X-ProxyPort' '80';
        proxy_set_header 'X-ProxyScheme' 'http';
spec:
  rules:
  - http:
      paths:
      - path: /{{ $ingressPath }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-nifi-service
            port:
              number: 8080
    {{- if .Values.ingress.host }}
    host: {{ .Values.ingress.host | quote }}
    {{ end }}
{{ end }}