
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nifi-service
spec:
  selector:
    podName: {{ .Release.Name }}-nifi-pod
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
