
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nifi-service
spec:
  selector:
    podName: {{ .Release.Name }}-nifi-pod
  ports:
  - name: "8080"
    protocol: TCP
    port: 8080
    targetPort: 8080
  {{- if .Values.openServicePorts.enabled -}}
  {{- $startPort := .Values.openServicePorts.startPort -}}
  {{- range $i := until (int .Values.openServicePorts.numberOfPorts) }}
  {{- $portNum := add $i $startPort }}
  - name: {{ $portNum | quote }}
    protocol: TCP
    port: {{ $portNum }}
    targetPort: {{ $portNum }}
  {{- end -}}
  {{- end -}}
